### PR TITLE
docs: fix typos and wording in README.md

### PR DESCRIPTION
**Pull request by jirihofman**
### Summary

Fixed wording and typos in readme only.

### CODE REVIEW

**Review by KarimMokhtar — APPROVED** [review]

**Comment by KarimMokhtar** [comment]
@jirihofman Thank you so much for your contribution.
But could you please follow the semantic PRs?

**Comment by jirihofman** [comment]
> But could you please follow the semantic PRs?
Done.

**Comment by KarimMokhtar** [comment]
@jirihofman  i think you need to change the commit not only the title

**Comment by jirihofman** [comment]
@KarimMokhtar Done. I thought so too, but this line from the actions confused me a bit
> No release type found in pull request title "Update README.md". Add a prefix to indicate what kind of release this pull request corresponds to

**Pull request merged**
