### PR TITLE
fix: Click event firing twice in Next.js applications

### PR DESCRIPTION
**Pull request by room9design**
### Summary

This package would have some strange behaviors in Next.js where the file upload window would pop up twice when the upload button was clicked. Upon investigation it was seen that the click event fired twice when the component was clicked. Adding a event.stopPropagaiton to the UploadWrapper and the input component stops this behavior, allowing the component to function as intended.

#### Key Changes

- Added event.stopPropagation to the UploadWrapper and input components.

### Check List

- [ ] The changes to the "Readme" file(if needed)
- [ ] The changes not breaking any old rule of the library or usage

### CODE REVIEW

**Comment by room9design** [comment]
Added necessary colon to title.

**Comment by room9design** [comment]
All necessary changes to pass semantic checks have been completed. Please revisit this pull rquest.

**Review by KarimMokhtar — APPROVED** [review]

**Review by KarimMokhtar — APPROVED** [review]

**Comment by KarimMokhtar** [comment]
@room9design Thank you so much for your contribution.  could you please fix the semantic pull request issue?

**Comment by room9design** [comment]
I'm confused, is there a place other than inside Github where I need to change the pull request title?

**Comment by KarimMokhtar** [comment]
> @KarimMokhtar I'm confused, is there a place other than inside Github where I need to change the pull request title?

I think you need to change the commit itself from “Fix” to “fix”

**Comment by room9design** [comment]
@KarimMokhtar Recommitted with updated commit message.

**Pull request merged**
