### PR TITLE
chore: remove console due to potential risk

### PR DESCRIPTION
**Pull request by saitharunsai**
### Summary

[Removed  Console Regarding  the Potential Risk?]

#### Key Changes

- [List the changes to look for in this PR]

### Check List

- [x] The changes to the "Readme" file(if needed)
- [x] The changes not break any old rule of the library or usage

### CODE REVIEW

**Comment by saitharunsai** [comment]
@KarimMokhtar  Is this Purposely kept? we can  make a new prop to remove all the dev things

**Review by KarimMokhtar — APPROVED** [review]

**Review by KarimMokhtar — CHANGES_REQUESTED** [review]
Could you please just change the commit msg to be semantic because the pipeline is failing?

**Comment by saitharunsai** [comment]
> Could you please just change the commit msg to be semantic because the pipeline is failing?

Updated Commit Message

**Review by KarimMokhtar — CHANGES_REQUESTED** [review]
The pipeline still failing.
Could you please start the commit msg with "chore: " without the double quotes and then you commit msg?

**Comment by tehroot** [comment]
Can you publish this to NPM as a new version please?

The console statement is still present in v2.3.4.

**Comment by KarimMokhtar** [comment]
Hi @tehroot . It will be published this weekend. Thanks for your interest.

**Comment by tehroot** [comment]
Thanks for the update!

**Comment by KarimMokhtar** [comment]
@tehroot @saitharunsai  Hello guys, Thanks for your contributions. 
Now it's published on v.2.3.5 please check.

**Pull request merged**
