### PR TITLE
Fix typescript output, make build and dev faster by using esbuild/vitest

### PR DESCRIPTION
**Pull request by jonluca**
### Summary

The typescript output was actually just `es` code output, not types. This fixes it so that the output is the actual declarations.

#### Key Changes

- Change build system to use esbuild, which is significantly faster
- Change test system to use vitest, which is significantly faster
- Change playground to use vite
- Fix typescript output
- Bump package versions

### CODE REVIEW

**Comment by KarimMokhtar** [comment]
@jonluca Could you solve the conflicts please?

**Comment by jonluca** [comment]
Done

**Comment by jonluca** [comment]
I'm not sure why it's failing, that commit isn't in this PR I believe?

**Comment by jonluca** [comment]
Recreated it here with only one commit https://github.com/KarimMokhtar/react-drag-drop-files/pull/89

**Pull request closed without merging**
