### PR TITLE
feat: added husky and lint-staged

### PR DESCRIPTION
**Pull request by Brandontam29**
### Summary

Added husky and lint-staged. I am new to open source and doing this kind of config. I want to know if this is what you were looking for. I will probably have to do some changes before merging because I am not sure if this is good.

#### Key Changes

Only modified the package.json. Ran `npm run test` but `Cannot find module 'react' from 'tests/DrawTypes.test.tsx'`.

### CODE REVIEW

**Comment by KarimMokhtar** [comment]
Hi @Brandontam29 ,
Thanks for your contribution, Actually we are not using tests right now as it needs a special configuration so there is no need for that command.
Also could you please try to take a branch of yours and check if the linting is working?
Second thing please make sure you are following the semantic PR rules so your code passes the pipeline.
Thanks again for your effort.

**Comment by Brandontam29** [comment]
I don't know if you received the notification, but I just pushed the branch with commit message changed. Thank you.

**Comment by Brandontam29** [comment]
I changed the title of the pr, sorry for the inconvenience. I hope it works this time.

**Comment by KarimMokhtar** [comment]
Hi @Brandontam29 ,
Have you tried it locally? I have tried to test if it's gonna lint the staged files or not but it seems that it's not working.
Could you please check?

**Comment by Brandontam29** [comment]
Let me test it this weekend. I have a few things going on right now.

**Comment by KarimMokhtar** [comment]
@Brandontam29  have you reached a new update on this or should i close the PR?

**Pull request closed without merging**
